name: flutter_sdk
description: Supertonic Flutter SDK TTS Example
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.6.0
  args: ^2.4.0
  path_provider: ^2.1.1
  just_audio: ^0.10.5
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/onnx/
    - assets/voice_styles/
  uses-material-design: true